### ISSUE TITLE
does this support sub accounts?

### ISSUE THREAD

**Issue by abelal83** [chatwork/sendgrid-stats-exporter#15]
This project looks like exactly what I was looking for. We however have multiple sub accounts, can the parent account details be supplied for it to pull stats from all sub accounts?

**Comment by ada-u** [comment]
@abelal83 Sorry for the late reply! 🙏 We cannot pull the stats of sub-accounts even if you use the parent account's credential due to the SendGrid's spec. We need to run an exporter for each sub-account.
